### ISSUE TITLE
Error when using multiple parents

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#227]
I’m using multiple parents. Everything works fine. However, if I set the spids column to a node on the same level but with a different parent, the following error appears:

vendor.js:564126 Cannot read property 'leftNeighbor' of null
TypeError: Cannot read property 'leftNeighbor' of null
    at Object.secondLinks (http://localhost:4200/scripts.js:1:168397)
    at http://localhost:4200/scripts.js:1:5664
    at http://localhost:4200/scripts.js:1:102478
    at http://localhost:4200/scripts.js:1:102967
    at Object.OrgChart.local._walk (http://localhost:4200/scripts.js:1:91284)
    at OrgChart.server._read (http://localhost:4200/scripts.js:1:102710)
    at OrgChart.server.read (http://localhost:4200/scripts.js:1:102109)
    at OrgChart._draw (http://localhost:4200/scripts.js:1:5084)
    at OrgChart._resizeHandler (http://localhost:4200/scripts.js:1:86292)
    at r (http://localhost:4200/scripts.js:1:22775)

**Comment by plamen-peshev** [comment]
It is limitation of spids

use clink intead

**Comment by sks4u** [comment]
But curved links have a complete different appearance. 

What exactly are the limitations of pids and where are they documented?

**Comment by sks4u** [comment]
I spoke with product management. Curved links are not an option. 

I also want you to notice, that we do not have control to the data of the data source. It typically comes from a database query defined by the user.

**Comment by plamen-peshev** [comment]
The issue has been addressed in the latest version

See https://jsfiddle.net/BALKANGraph/46tLnvdj/
