### ISSUE TITLE
Receive error when exporting to SVG

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#245]
Sadly, the error is not reproducible in a easy way.

> TypeError: Cannot read property 'removeChild' of null
    at OrgChart.xScrollUI.create (https://demo35.4plan.net/dashboard/de/scripts.eb780a4c453d76dd20ac.js:1:186576)
    at OrgChart._resizeHandler (https://demo35.4plan.net/dashboard/de/scripts.eb780a4c453d76dd20ac.js:1:85827)

**Comment by Miguel2426** [comment]
I have the same Issue exporting to PDF

**Comment by ZornitsaSerbezova** [comment]
Can you please post more details, because we don't have access to this site.

**Comment by ZornitsaSerbezova** [comment]
Please, download the latest version and try again.
