### ISSUE TITLE
Cannot read properties of undefined (reading 'scaleLessThen')

### ISSUE THREAD

**Issue by Panagiss** [BALKANGraph/OrgChartJS#701]
I was following these [examples ](https://code.balkan.app/org-chart-js/first-look#JS)from Balkan website but I have got to an error that goes to the Orgchart file which of course I cannot debug and also I coudn't find anything similar in the web.

Here is the error that I get on the browser's console:

```
orgchart.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'scaleLessThen')
    at OrgChart.t (orgchart.js:1:211205)
    at Object.node (orgchart.js:1:184599)
    at orgchart.js:1:7844
    at orgchart.js:1:131740
    at orgchart.js:1:132329
    at OrgChart.remote._proceed (orgchart.js:1:299185)
    at orgchart.js:1:298918
    at n.onload (orgchart.js:1:21545)
```

The orgchart file is straight from the website and also I downloaded it again to be sure.

Here is a sample code that produced that. Take in mind that I use Jinja2 in the .html files but that is what browser gets:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="/static/css/custom.css" -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/custom.css">
    <script src="/static/js/orgchart.js"></script>
    <title>Demo</title>
    
</head>
<body>
      <h1> Demo1 </h1>
<div style="width:100%; height:700px;" id="tree"/>
<script>
OrgChart.templates.ana.plus = '<circle cx="15" cy="15" r="15" fill="#ffffff" stroke="#aeaeae" stroke-width="1"></circle>'
    + '<text text-anchor="middle" style="font-size: 18px;cursor:pointer;" fill="#757575" x="15" y="22">{collapsed-children-count}</text>';

OrgChart.templates.itTemplate = Object.assign({}, OrgChart.templates.ana);
OrgChart.templates.itTemplate.nodeMenuButton = "";
OrgChart.templates.itTemplate.nodeCircleMenuButton = {
    radius: 18,
    x: 250,
    y: 60,
    color: '#fff',
    stroke: '#aeaeae'
};

OrgChart.templates.invisibleGroup.padding = [20, 0, 0, 0];

    var chart = new OrgChart(document.getElementById("tree"), {
        template: "belinda",
        align: OrgChart.ORIENTATION,
        nodeCircleMenu: {
            details: {
                icon: OrgChart.icon.details(24, 24, '#aeaeae'),
                text: "Details",
                color: "white"
            },
            edit: {
                icon: OrgChart.icon.edit(24, 24, '#aeaeae'),
                text: "Edit node",
                color: "white"
            }
        },
        nodeBinding: {
            field_0: "name",
            field_1: "title",
            email: "email",
            img_0: "img",
        },
        tags: {
            "department": {
                template: "group",
                nodeMenu:{
                    "edit": {
                        "text": "Edit employee"
                    }
                }
            },
            "ena-lead": {
                template: "invisibleGroup",
                subTreeConfig: {
                    orientation: OrgChart.orientation.bottom,
                    collapse: {
                        level: 1
                    }
                }
            },
            
            "None": {  template: "group_grey", groupName: "None", subTreeConfig:{layout: OrgChart.mixed,collapse: {level:1} }, } ,
            
            "dep1: {  template: "group_grey", groupName: "dep1", subTreeConfig:{layout: OrgChart.mixed,collapse: {level:1} }, } ,
            
            "dep2": {  template: "group_grey", groupName: "dep2", subTreeConfig:{layout: OrgChart.mixed,collapse: {level:1} }, } ,

            "dep3": {  template: "group_grey", groupName: "dep3", subTreeConfig:{layout: OrgChart.mixed,collapse: {level:1} }, } 
        },
        clinks: [
            { from: 11, to: 18 }
        ]
    });
    chart.load([ 
    
    { id: "ena-lead", name: "test1", tags:["ena-lead"]},
    
    { id: "None", pid: "ena-lead", tags: ["None", "department"], name: "None" },
    
    { id: "dep1", pid: "ena-lead", tags: ["dep1", "department"], name: "dep1" },
    
    { id: "dep2", pid: "ena-lead", tags: ["dep2", "department"], name: "dep2" },
    
    { id: "dep3", pid: "ena-lead", tags: ["dep3", "department"], name: "dep3" },
 
    { id: 1, stpid:"ena-lead", name: "user1", email: "user1@gmail.com", img: "static/img/user1.jpg"},

            { id: "xxxx1", stpid:"dep1", name: "user2",   title: "title2", email: "user2@gmail.com", img: "static/img/greek_shep.jpg"},
            { id: "xxxx2", stpid:"dep2", name: "user3",   title: "title3", email: "user3@gmail.com", img: "static/img/greek_shep.jpg"},
            { id: "xxxx3", stpid:"dep3", name: "user4",   title: "title4", email: "user4@gmail.com", img: "static/img/greek_shep.jpg"},

           { id: "xxxx4", pid:"xxxx2", name: "user5",   title: "title5", email: "user5@gmail.com", img: "static/img/greek_shep.jpg"},
           { id: "xxxx5", pid:"xxxx2", name: "user6",   title: "title6", email: "user6@gmail.com", img: "static/img/greek_shep.jpg"},
           { id: "xxxx6", pid:"xxxx3", name: "user7",   title: "title7", email: "user7@gmail.com", img: "static/img/greek_shep.jpg"},
    
</script> 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>
```

**Comment by Panagiss** [comment]
> "dep1: should be "dep1":

Good point but that was a typo in my post. It was not in the actual file.
Although I found the error after lot of trial/error. The ``` template: "group_grey"``` was causing the issue here. Maybe it's a deprecated template or whatever, but the point is that the error message was really off. Doesn't help at all

**Comment by Panagiss** [comment]
> We have added an error message in 8.08.03

I'm not sure if I have that exact one or a successor of it. How can you determine the exact version after the download of the file?
I only have the JS file. No folders or so.

**Comment by ZornitsaPesheva** [comment]
alert(OrgChart.VERSION)
