### ISSUE TITLE
Org-chart is crashing my other pages when i refresh other pages

### ISSUE THREAD

**Issue by joshuacos1977** [BALKANGraph/OrgChartJS#778]
I have a fully functional org-chart with database connection.I am able to filter based on the dropdown options like user's performance and department.However,the biggest issue is after adding department to the dropdown.Other part of the application crashes when i refresh.
here is the org-chart look like below:
![Screenshot 2023-07-26 101011](https://github.com/BALKANGraph/OrgChartJS/assets/28411895/8d502b27-c2db-4e57-ac8c-4cf97fdbeb66)
![Screenshot 2023-07-26 101123](https://github.com/BALKANGraph/OrgChartJS/assets/28411895/1cdca7d0-7311-4d5d-9ed8-c8a80b5a907b)

**Comment by joshuacos1977** [comment]
When i navigate some other page and refresh that page i am getting the error below on the console:
Uncaught TypeError: Cannot read properties of undefined (reading 'templates')
    at ./src/component/orgChart/OrganizationChart/OrganizationChart.jsx (OrganizationChart.jsx:4:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/component/orgChart/OrganizationChart/index.js (OrganizationChart.jsx:43:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/view/Reports/Tree.js (Sidebar.js:5:1)
    at options.factory (react refresh:6:1)

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in a simple code example:
https://code.balkan.app/org-chart-js/simple-example#JS

**Comment by ZornitsaPesheva** [comment]
Closing the issue as inactive.
